### ISSUE TITLE
Test cookie vmod fail after upgrade 4 -> 4.1

### ISSUE THREAD

**Issue by JoseGarciaRuiz** [varnish/varnish-modules#10]
Hello,
I have a CentOS 6.
I tried to install varnish-modules. I had Varnish 4, I noticed upgrade to 4.1 required in order to avoid vmodtool.py -w error.

I used:
rpm --nosignature -i https://repo.varnish-cache.org/redhat/varnish-4.1.el6.rpm
yum install varnish

(varnish service was running and I have not restarted yet, because it is serving pages).

cloned git varnish modules, and I followed instructions:
yum install varnish-libs-devel
./bootstrap
./configure
make check

I get an error at make check:
```
*    top   0.0 TEST Test cookie vmod
**   top   0.0 === server s1 {
**   s1    0.0 Starting server
**** s1    0.0 macro def s1_addr=127.0.0.1
**** s1    0.0 macro def s1_port=35641
**** s1    0.0 macro def s1_sock=127.0.0.1 35641
*    s1    0.0 Listen on 127.0.0.1 35641
**   top   0.0 === varnish v1 -vcl+backend {
**   s1    0.0 Started on 127.0.0.1 35641
**   v1    0.0 Launch
***  v1    0.0 CMD: cd ${pwd} && exec ${varnishd}  -d -n /tmp/vtc.26357.2f4c1aec/v1 -l 2m,1m,- -p auto_restart=off -p syslog_cli_traffic=off -p sigsegv_handler=on -p thread_pool_min=10 -p debug=+vtc_mode -a '127.0.0.1:0' -M '127.0.0.1 51704' -P /tmp/vtc.26357.2f4c1aec/v1/varnishd.pid
***  v1    0.0 CMD: cd /root/varnish-modules/src && exec /usr/sbin/varnishd  -d -n /tmp/vtc.26357.2f4c1aec/v1 -l 2m,1m,- -p auto_restart=off -p syslog_cli_traffic=off -p sigsegv_handler=on -p thread_pool_min=10 -p debug=+vtc_mode -a '127.0.0.1:0' -M '127.0.0.1 51704' -P /tmp/vtc.26357.2f4c1aec/v1/varnishd.pid
***  v1    0.0 PID: 26363
**** v1    0.0 macro def v1_pid=26363
**** v1    0.0 macro def v1_name=/tmp/vtc.26357.2f4c1aec/v1
***  v1    0.0 debug| Debug: Platform: Linux,2.6.32-573.18.1.el6.x86_64,x86_64,-junix,-smalloc,-smalloc,-hcritbit\n
***  v1    0.0 debug| \n
***  v1    0.0 debug| 200 292     \n
***  v1    0.0 debug| -----------------------------\n
***  v1    0.0 debug| Varnish Cache CLI 1.0\n
***  v1    0.0 debug| -----------------------------\n
***  v1    0.0 debug| Linux,2.6.32-573.18.1.el6.x86_64,x86_64,-junix,-smalloc,-smalloc,-hcritbit\n
***  v1    0.0 debug| varnish-4.1.2 revision 0d7404e\n
***  v1    0.0 debug| \n
***  v1    0.0 debug| Type 'help' for command list.\n
***  v1    0.0 debug| Type 'quit' to close CLI session.\n
***  v1    0.0 debug| Type 'start' to launch worker process.\n
***  v1    0.0 debug| \n
**** v1    0.1 CLIPOLL 1 0x1 0x0
***  v1    0.1 CLI connection fd = 10
***  v1    0.1 CLI RX  107
**** v1    0.1 CLI RX| ffyiqrnzhcbplspwqdyeeacuzekxyyad\n
**** v1    0.1 CLI RX| \n
**** v1    0.1 CLI RX| Authentication required.\n
**** v1    0.1 CLI TX| auth 0c1b408d02494ab049c59778c6fa3b4cbdcfcc88863fb28c1417330943ab771d\n
***  v1    0.1 CLI RX  200
**** v1    0.1 CLI RX| -----------------------------\n
**** v1    0.1 CLI RX| Varnish Cache CLI 1.0\n
**** v1    0.1 CLI RX| -----------------------------\n
**** v1    0.1 CLI RX| Linux,2.6.32-573.18.1.el6.x86_64,x86_64,-junix,-smalloc,-smalloc,-hcritbit\n
**** v1    0.1 CLI RX| varnish-4.1.2 revision 0d7404e\n
**** v1    0.1 CLI RX| \n
**** v1    0.1 CLI RX| Type 'help' for command list.\n
**** v1    0.1 CLI RX| Type 'quit' to close CLI session.\n
**** v1    0.1 CLI RX| Type 'start' to launch worker process.\n
**** v1    0.1 CLI TX| vcl.inline vcl1 << %XJEIFLH|)Xspa8P\n
**** v1    0.1 CLI TX| vcl 4.0;\n
**** v1    0.1 CLI TX| backend s1 { .host = "127.0.0.1"; .port = "35641"; }\n
**** v1    0.1 CLI TX| \n
**** v1    0.1 CLI TX| \n
**** v1    0.1 CLI TX| \timport cookie from "/root/varnish-modules/src/.libs/libvmod_cookie.so";\n
**** v1    0.1 CLI TX| \n
**** v1    0.1 CLI TX| \tsub vcl_recv {\n
**** v1    0.1 CLI TX| \t\tcookie.set("cookie1", "cookie1BAD");\n
**** v1    0.1 CLI TX| \t\tcookie.set("cookie2", "cookie2value");\n
**** v1    0.1 CLI TX| \t\tcookie.set("cookie3", "cookie3value");\n
**** v1    0.1 CLI TX| \t\tcookie.set("cookie4", "cookie4value");\n
**** v1    0.1 CLI TX| \t\tcookie.set("cookie1", "cookie1value");\n
**** v1    0.1 CLI TX| \t\tcookie.delete("cookie2");\n
**** v1    0.1 CLI TX| \t\tset req.http.X-foo = cookie.get_string();\n
**** v1    0.1 CLI TX| \t}\n
**** v1    0.1 CLI TX| \tsub vcl_deliver {\n
**** v1    0.1 CLI TX| \t\tset resp.http.X-foo = req.http.X-foo;\n
**** v1    0.1 CLI TX| \t}\n
**** v1    0.1 CLI TX| \n
**** v1    0.1 CLI TX| %XJEIFLH|)Xspa8P\n
***  v1    0.1 CLI RX  106
**** v1    0.1 CLI RX| Message from VCC-compiler:\n
**** v1    0.1 CLI RX| Could not load VMOD cookie\n
**** v1    0.1 CLI RX| \tFile name: /root/varnish-modules/src/.libs/libvmod_cookie.so\n
**** v1    0.1 CLI RX| \tdlerror: /root/varnish-modules/src/.libs/libvmod_cookie.so: cannot open shared object file: Permission denied\n
**** v1    0.1 CLI RX| ('<vcl.inline>' Line 5 Pos 16)\n
**** v1    0.1 CLI RX|         import cookie from "/root/varnish-modules/src/.libs/libvmod_cookie.so";\n
**** v1    0.1 CLI RX| ---------------######----------------------------------------------------------\n
**** v1    0.1 CLI RX| \n
**** v1    0.1 CLI RX| Running VCC-compiler failed, exited with 2\n
**** v1    0.1 CLI RX| VCL compilation failed
---- v1    0.1 FAIL VCL does not compile
*    top   0.1 RESETTING after ../src/tests/cookie/01-set-delete-produce.vtc
**   s1    0.1 Waiting for server (4/-1)
**** s1    0.1 macro undef s1_addr
**** s1    0.1 macro undef s1_port
**** s1    0.1 macro undef s1_sock
**   v1    0.1 Wait
**** v1    0.1 CLI TX| backend.list
***  v1    0.2 CLI RX  101
**** v1    0.2 CLI RX| Unknown request in manager process (child not running).\n
**** v1    0.2 CLI RX| Type 'help' for more info.
**** v1    1.0 STDOUT poll 0x10
**   v1    1.0 R 26363 Status: 0000 (u 0.003999 s 0.003999)
*    top   1.0 TEST ../src/tests/cookie/01-set-delete-produce.vtc FAILED

#     top  TEST ../src/tests/cookie/01-set-delete-produce.vtc FAILED (1.006) exit=1
make[1]: *** [../src/tests/cookie/01-set-delete-produce.vtc] Error 2
make[1]: Leaving directory `/root/varnish-modules/src'
make: *** [check-recursive] Error 1
```
The error: libvmod_cookie.so: cannot open shared object file: Permission denied
The file exists, and I tried to increase permissions, but problem persists.

Any suggestion will be apreciated.

Thanks.

**Comment by lkarsten** [comment]
My first guess would be that varnishd is dropping to user nobody/varnish, and as such doesn't have access in /root/.

Can you try to build the package as an ordinary non-privileged user? When everything works you can run sudo make install (or su - and then make install if you don't have sudo)

**Comment by JoseGarciaRuiz** [comment]
I just exec from a normal user:
git clone https://github.com/varnish/varnish-modules
cd varnish-modules
./bootstrap
./configure

And from another console with root I exec:
cd /home/myuser/varnish-modules
make check

I got a different error at same cookie test: 
open(vcl_vcl1/vgc.so) = vcl_vcl1/vgc.so: failed to map segment from shared object: Operation not permitted

**Comment by lkarsten** [comment]
Is selinux enabled? Please add a full varnishlog if the problem persists.

**Comment by lkarsten** [comment]
Hold on. Re-reading your post. Are you still trying to run the test suite as root? Why? There is no requirement for it to run with extra privileges.

**Comment by JoseGarciaRuiz** [comment]
sestatus
SELinux status:                 disabled

I am not running test suite, i just follow steps at readme. I just exec: make check
I tried it with a user with lower privileges and i get other errors as expected.
make check run test suite, not sure why.
I tried to get a varnishlog, but no log is generated, just empty.

**Comment by JoseGarciaRuiz** [comment]
Varnish is upgraded to 4.1, it is running.
No results at Google.

This is the most important info regarding the problem:
Could not load VMOD cookie
File name: /root/varnish-modules/src/.libs/libvmod_cookie.so
dlerror: /root/varnish-modules/src/.libs/libvmod_cookie.so: cannot open shared object file: Permission denied
('<vcl.inline>' Line 5 Pos 16)
        import cookie from "/root/varnish-modules/src/.libs/libvmod_cookie.so";
---------------######----------------------------------------------------------

Running VCC-compiler failed, exited with 2
VCL compilation failed
v1    0.1 FAIL VCL does not compile
top   0.1 RESETTING after ../src/tests/cookie/01-set-delete-produce.vtc

**Comment by lkarsten** [comment]
Hi.

I've changed the installation steps to make it more clear what should be run as an ordinary user and what needs extra privileges: https://github.com/varnish/varnish-modules/commit/3a0f124a7debe42c2848bf254351013cd39039cd .

Please delete your checkout completely, re-clone as an ordinary user to and try the updated install steps.

**Comment by JoseGarciaRuiz** [comment]
Hi good morning,
thanks for support.

I keep getting the same error:
`dlopen(vcl_vcl1/vgc.so) = vcl_vcl1/vgc.so: failed to map segment from shared object: Operation not permitted
CLI RX| Running dlopen failed, exited with 1
CLI RX| VCL compilation failed
FAIL VCL does not compile
0.3 RESETTING after ../src/tests/cookie/01-set-delete-produce.vtc`

But Im not sure if problem is related about VMODS or about 4.1 upgrade.

**Comment by lkarsten** [comment]
Hi.

Timing this out now. Please open another issue you think this is a problem with varnish-modules.
