### ISSUE TITLE
softpurge

### ISSUE THREAD

**Issue by ManuelRighi** [varnish/varnish-modules#101]
Hello,
with softpurge is possible to purge specific url ?
Actually I use this sintax in VCL

if (req.method == "PURGE" || req.method == BAN") {
ban("req.url ~ ^" + req.url + "$ && req.http.host == " + req.http.host);
return (purge);

Thanks
Manuel

**Comment by daghf** [comment]
Hi

Please use one of the options listed on http://varnish-cache.org/support/index.html for questions. This list is for bug reports only.
