### ISSUE TITLE
Error while loading xkey vmod for varnish 5.2.1

### ISSUE THREAD

**Issue by hardik8585** [varnish/varnish-modules#108]
hi, I am getting below error while laoding vmod in varnish 5.2.1 cache.

dlerror: /usr/lib64/varnish/vmods/libvmod_xkey.so: undefined symbol: vmod_event

There is not init_function also in vmod src.

I used varnish-modules-0.10.2 with varnish 5.2.1

**Comment by gquintard** [comment]
please use the varnish-misc mailing list for questions: http://varnish-cache.org/support/index.html
