### ISSUE TITLE
bodyaccess

### ISSUE THREAD

**Issue by opensubtitles** [varnish/varnish-modules#109]
Hi,

varnishd (varnish-5.2.1 revision NOGIT)

```
   if (req.method == "POST" && req.http.host ~ "^api.opensubtitles.org") {
        std.cache_req_body(1KB);
        if (bodyaccess.rematch_req_body("DisabledUA") == 1) {
                return (synth(429, "Too Many Requests"));
        }
   }
```

if POST is more than 1KB, then Varnish close connection without any http return code/response. Not sure if this is desired behavior, for me it seems like bug.

```
214.125.201.209 - - [27/Mar/2018:12:08:54 +0200] "POST http://api.opensubtitles.org:80/xml-rpc HTTP/1.0" - 0 "-" "xmlrpc-epi-php/0.2 (PHP)"
```

**Comment by Dridi** [comment]
It sounds like you should open an issue in varnish-cache instead, unless it's only happening when using `vmod-bodyaccess`?

**Comment by opensubtitles** [comment]
I am not sure, if it happens on "std.cache_req_body(1KB);" or "if (bodyaccess.rematch_req_body("DisabledUA") == 1) {" - it might, because probably it is empty...

**Comment by Dridi** [comment]
Can you confirm the connection closure if you comment out `vmod-bodyaccess` usage?

**Comment by opensubtitles** [comment]
I can confirm problem is with "std.cache_req_body(1KB);", I will open ticket in varnish-cache
