### ISSUE TITLE
Download missing for 0.14

### ISSUE THREAD

**Issue by andrerom** [varnish/varnish-modules#113]
0.14 missing on https://download.varnish-software.com/varnish-modules/

**Comment by andrerom** [comment]
That said, it seems 0.14 won't really help much in getting things of the ground with Varnish 6.0?
ref: https://github.com/varnish/varnish-modules/compare/0.14.0...master

**Comment by dmatetelki** [comment]
Hi @andrerom, I'll upload the 0.14 version and check the VC-6 compatibility today.

**Comment by dmatetelki** [comment]
I've uploaded version 0.14 to  https://download.varnish-software.com/varnish-modules/

It is not compatible with VC-6, but the current master is. Let me tag it and release 0.15.
