### ISSUE TITLE
alpine:3.7 FAIL tests/tcp/02-congestion.vtc 

### ISSUE THREAD

**Issue by strowi** [varnish/varnish-modules#115]
Hi,

i  just tried compiing this in docker (alpine:3.7). It doesn't matter if i use the alpine-package or compile varnish from source.

```
FROM alpine:3.7

ARG BUILD_TOOLS=" \
    varnish-dev \
    automake \
    autoconf \
    libtool \
    python \
    make \
    git \
  "

RUN apk --update --no-cache add \
  varnish \
  $BUILD_TOOLS

RUN cd /tmp \
  && git clone --depth=1 https://github.com/varnish/varnish-modules.git \
  && cd varnish-modules \
  && ./bootstrap \
  && ./configure --prefix=/usr \
  && make -j4 \
  && make check \
  && make install
```
attached the test-suite.log
[t.txt](https://github.com/varnish/varnish-modules/files/2102453/t.txt)

regards,
Roman

**Comment by Dridi** [comment]
Typo in my commit, I meant to close #125.

**Comment by Dridi** [comment]
There is nothing in the log, which means the systematic `-1` coming from `tcp.congestion_algorithm()` tells us this system has no `struct tcp_info`.

**Comment by csandanov** [comment]
I also had the same failure during `make check` with version 0.15.0 on Alpine 3.8, works fine on `master`, it would be great if a fix was released to freeze the version.
