### ISSUE TITLE
the cookie.delete() can be delete multiple value?

### ISSUE THREAD

**Issue by redbox-cdn** [varnish/varnish-modules#116]
Hi
the `cookie.delete()` can be delete multiple value?

it does not work

```
cookie.parse(req.http.Cookie);
cookie.delete("aaa","bbb");
set req.http.cookie = cookie.get_string();
```

it is work
```
cookie.parse(req.http.Cookie);
cookie.delete("aaa");
cookie.delete("bbb");
set req.http.cookie = cookie.get_string();
```

**Comment by Dridi** [comment]
There is currently no support for vararg functions in VCL, if calling `cookie.delete()` multiple times works fine for you there is nothing more we can do.
