### ISSUE TITLE
document python-docutils requirement or handle missing rst2man

### ISSUE THREAD

**Issue by nigoroll** [varnish/varnish-modules#125]
ref #119 (actually the wrong ticket for this) #123 

the requirement of python-docutils should be documented. A missing `rst2man` should either be handled or `rst2man` should be a hard requirement during `configure`.

Originally reported by @tristanbes

**Comment by tristanbes** [comment]
Actually, if a document for *all* required depandancies to compile the project, it would be great. Thanks for opening this issue.

**Comment by Dridi** [comment]
Fixed in https://github.com/varnish/varnish-modules/commit/6399b9129371d4edd3cea57bfbdd98bb720939bd.
