### ISSUE TITLE
xkey: refresh object after softpurge()

### ISSUE THREAD

**Issue by nd2s** [varnish/varnish-modules#129]
How can one automatically refresh/reload all of the invalidated objects after a call to `xkey.softpurge()`?

**Comment by gquintard** [comment]
Closing at it isn't an bug, please use the varnish-misc mailing list for such questions (http://varnish-cache.org/support/index.html).

The feature you ask about isn't implemented in xkey, and you probably don't want it either as it would potentially mean unleashing a thundering herd onto the origin when you invalidate a too many objects.
