### ISSUE TITLE
Does xkey have limits on number of tags?

### ISSUE THREAD

**Issue by andrerom** [varnish/varnish-modules#130]
Looking into expanding the doc here a bit, I'm wondering if xkey has any know limits on number of tags on responses and on purges(`xkey.[soft]purge()`) besides Varnish headers limits imposed by [http_resp_hdr_len](https://varnish-cache.org/docs/6.1/reference/varnishd.html#http-resp-hdr-len) and [http_max_hdr](https://varnish-cache.org/docs/6.1/reference/varnishd.html#http-max-hdr) configurations?

**Comment by gquintard** [comment]
no, but that would have been a question for varnish-misc@varnish-cache.org
