### ISSUE TITLE
xkey stats

### ISSUE THREAD

**Issue by benzvan** [varnish/varnish-modules#145]
I'd love to be able to track stats on xkey use including number of keys and size of key storage space. I don't currently see anything coming out of `varnishstat` related to these metrics in varnish 6.

**Comment by gquintard** [comment]
Hi @benzvan,

`xkey` is considered feature-complete meaning that we aren't against studying pull requests, but we won't invest development time into new features.

**Comment by benzvan** [comment]
OK. Would you consider merging a pull request for this new feature?

**Comment by gquintard** [comment]
the policy (in the `README`) is that we will only accept bug and security fixes for that vmod

**Comment by nigoroll** [comment]
Re @benzvan 

> OK. Would you consider merging a pull request for this new feature?

my fork https://github.com/nigoroll/varnish-modules is starting to diverge anyway and I would consider one.

**Comment by gquintard** [comment]
So, let me walk that one back after having talked to the team: we'll take PRs as long as the code is clean and useful to the majority of users.

@nigoroll, repos are pretty much aligned at the moment, aren't they?

**Comment by nigoroll** [comment]
@gquintard Oh right, I actually missed the fact that you did pick up our commits. Thank you :)

**Comment by benzvan** [comment]
ok. I feel like visibility should be useful for the majority of users, so I'll get a story on our backlog for this.
