### ISSUE TITLE
RFC: dynamic header names

### ISSUE THREAD

**Issue by nigoroll** [varnish/varnish-modules#147]
Hi,
I would like to ask for feedback / coordination on the following improvement idea:

I need a way to set headers with dynamic names. Until varnish-cache may support such use cases, the obvious place to add this functionality would be the `header` vmod.
A full implementation would probably need all the existing `header` Functions except for regsub with a `HTTP` and `STRING` arguments instead of `HEADER`.
The obvious suggestion would be to add Functions prefixed by `dyn_`, so vcl could look like

```
header.dyn_append(req, "MyName", "myval");
header.dyn_copy(req, "MyName", req, "Othername");
myvar.set(header.dyn_get(req, "MyName", "^prefix"));
header.dyn_remove(req, "MyName", "^prefix");
```

Obviously there are infinitely many alternatives like a separate vmod, optional arguments, whatever.

I would welcome feedback and ideas, preferably better ideas than mine :)

**Comment by nigoroll** [comment]
never mind, I had a better idea for which I will open a PR

**Comment by rezan** [comment]
Just an FYI, this VMOD is considered feature complete:

https://github.com/varnish/varnish-modules/blob/master/README.rst#feature-complete-vmods

**Comment by nigoroll** [comment]
it is up to you if you want to accept PRs or not.
But fortunately you did just merge #141 and I do not think that the "feature complete" status makes much sense for a vmod with a name "header".

**Comment by gquintard** [comment]
Just a heads-up, I'm still supposed to get vmod_header in core via
vmod_std, so we may not even have to have this discussion.

**Comment by nigoroll** [comment]
yes, I support that idea.
But I would actually prefer to keep the name `header`
