### ISSUE TITLE
Master build it broken with bodyaccess vmod

### ISSUE THREAD

**Issue by darjisanket** [varnish/varnish-modules#154]
I am trying to make with latest 6.0.6 and facing below error:

 VMODTOOL vcc_bodyaccess_if.c
  CC       vmod_bodyaccess.lo
vmod_bodyaccess.c: In function 'bodyaccess_bcat':
vmod_bodyaccess.c:170:6: error: passing argument 1 of 'VRB_Iterate' from incompatible pointer type [-Werror]
      vsb);
      ^
In file included from vmod_bodyaccess.c:37:0:
/usr/include/varnish/cache/cache_varnishd.h:325:9: note: expected 'struct req *' but argument is of type 'struct worker *'
 ssize_t VRB_Iterate(struct req *, objiterate_f *func, void *priv);
         ^
vmod_bodyaccess.c:170:6: error: passing argument 2 of 'VRB_Iterate' from incompatible pointer type [-Werror]
      vsb);
      ^
In file included from vmod_bodyaccess.c:37:0:
/usr/include/varnish/cache/cache_varnishd.h:325:9: note: expected 'int (*)(void *, int,  const void *, ssize_t)' but argument is of type 'struct vsl_log * const'
 ssize_t VRB_Iterate(struct req *, objiterate_f *func, void *priv);
         ^
vmod_bodyaccess.c:170:6: error: too many arguments to function 'VRB_Iterate'
      vsb);
      ^
In file included from vmod_bodyaccess.c:37:0:
/usr/include/varnish/cache/cache_varnishd.h:325:9: note: declared here
 ssize_t VRB_Iterate(struct req *, objiterate_f *func, void *priv);
         ^
vmod_bodyaccess.c: In function 'vmod_hash_req_body':
vmod_bodyaccess.c:185:35: error: 'BS_CACHED' undeclared (first use in this function)
  if (ctx->req->req_body_status != BS_CACHED) {
                                   ^
vmod_bodyaccess.c:185:35: note: each undeclared identifier is reported only once for each function it appears in
vmod_bodyaccess.c: In function 'vmod_len_req_body':
vmod_bodyaccess.c:216:35: error: 'BS_CACHED' undeclared (first use in this function)
  if (ctx->req->req_body_status != BS_CACHED) {
                                   ^
vmod_bodyaccess.c: In function 'vmod_rematch_req_body':
vmod_bodyaccess.c:245:35: error: 'BS_CACHED' undeclared (first use in this function)
  if (ctx->req->req_body_status != BS_CACHED) {
                                   ^
vmod_bodyaccess.c: In function 'vmod_log_req_body':
vmod_bodyaccess.c:308:35: error: 'BS_CACHED' undeclared (first use in this function)
  if (ctx->req->req_body_status != BS_CACHED) {
                                   ^
vmod_bodyaccess.c:314:6: error: passing argument 1 of 'VRB_Iterate' from incompatible pointer type [-Werror]
      &log_ctx);
      ^
In file included from vmod_bodyaccess.c:37:0:
/usr/include/varnish/cache/cache_varnishd.h:325:9: note: expected 'struct req *' but argument is of type 'struct worker *'
 ssize_t VRB_Iterate(struct req *, objiterate_f *func, void *priv);
         ^
vmod_bodyaccess.c:314:6: error: passing argument 2 of 'VRB_Iterate' from incompatible pointer type [-Werror]
      &log_ctx);
      ^
In file included from vmod_bodyaccess.c:37:0:
/usr/include/varnish/cache/cache_varnishd.h:325:9: note: expected 'int (*)(void *, int,  const void *, ssize_t)' but argument is of type 'struct vsl_log * const'
 ssize_t VRB_Iterate(struct req *, objiterate_f *func, void *priv);
         ^
vmod_bodyaccess.c:314:6: error: too many arguments to function 'VRB_Iterate'
      &log_ctx);
      ^
In file included from vmod_bodyaccess.c:37:0:
/usr/include/varnish/cache/cache_varnishd.h:325:9: note: declared here
 ssize_t VRB_Iterate(struct req *, objiterate_f *func, void *priv);
         ^
cc1: all warnings being treated as errors
make[2]: Leaving directory `/usr/redsky/src/varnish-modules/src'
make[2]: *** [vmod_bodyaccess.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by nigoroll** [comment]
try the 6.0-lts branch?

**Comment by darjisanket** [comment]
Sure it works but I wanted latest xkey changes committed in master

**Comment by nigoroll** [comment]
Then I guess your request would be to backport the key changes to the 6.0 branch

**Comment by darjisanket** [comment]
Yes, Do we have any timeline when it would be backported to 6.0

**Comment by gquintard** [comment]
Hi, as it's an LTS, no new features are planned to land in that branch, only bugfixes. That said, if someone wants to open a PR with the work done, I'll happily merge it.
