### ISSUE TITLE
Versions and branches (varnish-6.4.0)

### ISSUE THREAD

**Issue by ingvarha** [varnish/varnish-modules#155]
There is no git branch for varnish-6.4.0. Master branch builds on varnish-6.4.0.

Also, for distribution downstream (fedora/epel for me), please consider bumping the release number and/or figure out how versions are thought to work with the current branching. "What is the current version of varnish-modules" is quite difficult to answer. Here are some variants that may appear unless you figure out a uniform scheme:

varnish-modules-0.15.1-0.8.20200317git21d0c84.el7
varnish-modules-0.15.0-8.44patcheslater.605lts.el7

Ingvar

**Comment by gquintard** [comment]
as discussed on IRC: https://github.com/varnish/varnish-modules/tree/6.4

let me know if that works for you, and I can definitely tag it

**Comment by gquintard** [comment]
so, do you want a `6.4.1`, or should we use the `6.4.0` version as it hasn't been tagged?

**Comment by ingvarha** [comment]
The 6.4 branch builds fine against varnish-6.4.0 in fedora. For me, just keeping a single branch 6.4 for varnish-6.4.x works fine, and then tag releases for each version of varnish that is released. For example, varnish-modules-0.16.0 for varnish-6.4.0, varnish-modules-0.16.1 for a future varnish-6.4.1, and so on.

**Comment by gquintard** [comment]
I'm sorry, my question was more: we'll need a new version soon (just got some fixes), so should it be 6.4.1, or 6.4.0?

**Comment by ingvarha** [comment]
A new version of varnish, or a new version of varnish-modules?

For varnish-modules, either continue the current scheme and call it varnish-modules-0.16.0, or name it after the varnish release it should be built for; varnish-modules-6.4.0. The problem with the latter is what you should call it if you have to make a new version of varnish-modules for the same version of varnish. varnish-modules-6.4.0.1 starts sounding silly :-)

Ingvar

**Comment by gquintard** [comment]
> A new version of varnish, or a new version of varnish-modules?
PROTIP: don't send comment at 2am.... I meant `varnish-modules`, so `0.16.0` (the `configure.ac` is ready, but the commit was never tagged), or `1.16.1` (if you already "used" the `1.16.0` number)

**Comment by ingvarha** [comment]
You still confuse me. 0.16.0 or 1.16.0? :-D

I haven't "used" anything yet. I test-packaged a "0.16.0 prerelease" based on a git checkout from the 6.4 branch. 0.16.0 is fine by me.

**Comment by gquintard** [comment]
pheeew, Imma stop trying to type, and just go with `0.16.0`. We can then bury this ticket and forget how dumb I'm being :-)

I'll ping you once I've backported the fixes and tagged the release

**Comment by gquintard** [comment]
`varnish-modules-0.16.0` has been tagged (`0.16.0` too), so I'll close this, yell if something is off.
