### ISSUE TITLE
xkey_test12 fails, branch 6.4 on 32 bit

### ISSUE THREAD

**Issue by ingvarha** [varnish/varnish-modules#157]
I started test building varnish-modules branch 6.4 on misc arches yesterday.

xkey_test12 fails on epel-6-i386. Log attached.

Ingvar

**Comment by ingvarha** [comment]
[xkey_test12.log](https://github.com/varnish/varnish-modules/files/4347628/xkey_test12.log)

**Comment by ingvarha** [comment]
Reproduced with same error on 32-bit ppc, both on Ubuntu Xenial and Gentoo latest rolling relase.

"Not true: XKEY.g_hashhead_bytes (68) == 104 (104)"

**Comment by ingvarha** [comment]
For what it's worth, here's a variant of xkey/test12.vtc with values that works on 32 bit. The numbers are often, in the ballpark of half of their 64 bit sisters.


[test12.vtc.txt](https://github.com/varnish/varnish-modules/files/4349022/test12.vtc.txt)

**Comment by Dridi** [comment]
Slap a `feature 64bit` statement at the beginning of the test and it will be skipped on 32bit arches.

**Comment by benzvan** [comment]
This makes sense. The bytes used by the hashhead struct will change with architecture due to the size of the pointers it contains.

**Comment by benzvan** [comment]
We're going to add this into our PR for #159
