### ISSUE TITLE
STRING_LIST still being used

### ISSUE THREAD

**Issue by ingvarha** [varnish/varnish-modules#158]
According to the make output, a depricated element "STRING_LIST" is still used, while it was(?) discontinued "before the 2019-09-15 release".

Seems to still be working, though.

Ingvar

ingvar@notteroy:~/src/varnish-modules-0.16.0$ make -j2
make  all-recursive
make[1]: Entering directory '/home/ingvar/src/varnish-modules-0.16.0'
Making all in src
make[2]: Entering directory '/home/ingvar/src/varnish-modules-0.16.0/src'
  VMODTOOL vcc_bodyaccess_if.c
  VMODTOOL vcc_cookie_if.c
  VMODTOOL vcc_header_if.c
  VMODTOOL vcc_saintmode_if.c
########################################################################

STRING_LIST will be discontinued before the 2019-09-15 release

Please switch to STRANDS

########################################################################
  VMODTOOL vcc_tcp_if.c

**Comment by ingvarha** [comment]
Btw, this is branch 6.4 on varnish-6.4.0

**Comment by xordspar0** [comment]
I think the `-j2` is hiding the fact that this warning is happening during the compilation of vmod_header. Here's the only reference to STRING_LIST in this repo:

https://github.com/varnish/varnish-modules/blob/f771780801b5cf8b77954226a4f623fac759cd1e/src/vmod_header.vcc#L32
