### ISSUE TITLE
configure gives no warning when trying to build against incompatible versions of varnish

### ISSUE THREAD

**Issue by ingvarha** [varnish/varnish-modules#161]
Thanks for the 0.16.0 release. It is been built against varnish-6.4.0 for Fedora as I write this.

Just a small thing: The configure script will happily set up the build for previous versions of varnish, like 6.3.2, but the build will fail.

Please consider making the configure script probe for compatible versions of varnish.

Ingvar

**Comment by gquintard** [comment]
thank you for the bug report. This has been fixed with c361828 and backported in 2daf752
