### ISSUE TITLE
No release or branch compatible with 6.1

### ISSUE THREAD

**Issue by Bilge** [varnish/varnish-modules#169]
I cannot build 6.0, 6.0-lts or 6.2 branches for 6.1. None of the releases are compatible, either.

6.0 fails with

>vmod_saintmode.c: In function ‘healthy’:
vmod_saintmode.c:272:17: error: ‘const struct director’ has no member named ‘healthy’
   return (sm->be->healthy(sm->be, bo, changed));

6.2 fails with 

>vmod_header.c:196:1: error: no previous prototype for ‘vmod_event_function’ [-Werror=missing-prototypes]
 vmod_event_function(VRT_CTX, struct vmod_priv *priv, enum vcl_event_e e)
 ^~~~~~~~~~~~~~~~~~~

**Comment by gquintard** [comment]
`6.1` wasn't created because it was already EOL when we moved to the one-branch-per-version model, that being said, I understand the confusion of seeing a "hole" in the series, so I pushed `6.1` to the repo. BUT I really need to stress that this Varnish version is EOL and shouldn't be used.

**Comment by Bilge** [comment]
@gquintard As advised, I have upgraded.
