### ISSUE TITLE
vsthrottle stats and http header

### ISSUE THREAD

**Issue by aleemb** [varnish/varnish-modules#17]
Would it be possible to add a debug HTTP header or collect server side stats? The typical headers are  `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` (GitHub, Twitter, etc).

**Comment by daghf** [comment]
Hi @aleemb 

We can probably add a function for outputting the current token quota available for a given key, which would map well to the `X-RateLimit-Remaining` header.

`X-RateLimit-Limit` would just be whatever was specified for vsthrottle's `limit` argument?

I'm not sure `X-RateLimit-Reset` maps very well to vsthrottle. Vsthrottle does token bucket rate limiting. This means each token drips in at a steady rate of 1 per `period`/`limit` seconds. If by `X-RateLimit-Reset`  we mean what's the next time this client gets another token that would be the above calculation. If we take it to mean what is the time that this client regains its full quota, that would be after at most `period` time has passed.

Any ideas/thoughts on this?

I'll go ahead and implement the current token quota stat.

**Comment by daghf** [comment]
Pushed 4ec614e8970d8fc69c64ec48fcb5d29743d461a6 which adds `vsthrottle.remaining()` that lets you set the `X-RateLimit-Remaining`, 

Then you can do e.g., 
<pre>
sub vcl_deliver {
    set resp.http.X-RateLimit-Remaining = vsthrottle.remaining(client.identity, 100, 60m);
}
</pre>

With the assumptions mentioned above, you can set the other headers via something like `set resp.http.X-RateLimit-Limit = "100";` and `set resp.http.X-RateLimit-Reset = (60 * 60) / 100.0;`

**Comment by aleemb** [comment]
Awesome, thanks much! Makes sense about the reset stuff. Showing the `X-Rate-Limit` isn't that useful to be honest other than for large scale APIs with separate quotas for different API endpoints--in which case this makes it self documenting.

**Comment by gurvkm** [comment]
I am stuck with an issue in VCL. I am trying to show CAPTCHA to the user who hits more than 5 times in a second. So i am using vsthrottle for it.
if (vsthrottle.is_denied ( req.http.client.ip, 5, 1s)) {
                       
			return (synth(452));

	        }

in synth 452 i have written the code for showing CAPTCHA. But after verifying CAPTCHA i want to allow the user to hit the url without showing him CAPTCHA again. For that i need to reset the number of count values to 0 or remove that user's IP from the list of vsthrottle. How can i do this. Please help me in this case.

**Comment by gquintard** [comment]
Hi, as this is not a bug, please join us on irc, or send a message to the varnish-misc mailing list to discuss this.

You can also check https://varnish-cache.org/support/index.html for more help options
