### ISSUE TITLE
Build instructions out of date

### ISSUE THREAD

**Issue by Bilge** [varnish/varnish-modules#170]
The readme pretends you can start building by running `./configure`, but `./configure` does not exist. The actual build steps I had to use were as follows:

1. libtoolize 
2. aclocal
3. autoheader
4. automake --force-missing --add-missing
5. autoconf
6. ./configure
7. make

**Comment by Dridi** [comment]
The README instructs you to run `./configure` when you build a release archive:

https://github.com/varnish/varnish-modules#installation

If you want to work from a git clone of the repository, you have different instructions:

https://github.com/varnish/varnish-modules#development

**Comment by Bilge** [comment]
I wish it were as simple as you're pretending. Where's `./configure` in [these releases](https://github.com/varnish/varnish-modules/releases)? But I suppose you're referring *only* to [these releases](https://download.varnish-software.com/varnish-modules/) which haven't been updated in over two years, right? Even then, how does anyone know which release of the modules is compatible with which version of Varnish? I have not found a single release that's compatible with 6.1.

**Comment by Dridi** [comment]
I'm referring to the two-years-old release archives, which could incidentally also be uploaded along with "github releases". That may have been left in this state after moving from one development branch to one per major Varnish release. By the way Varnish 6.1 compatibility is a different topic, and you already opened #169 for that matter. I'll let @gquintard deal both tickets, but you shouldn't be using Varnish 6.1 since it's no longer supported.

https://varnish-cache.org/releases/index.html

**Comment by Bilge** [comment]
It is my mistake I didn't realize there are two sets of installation instructions depending on which release type you're using but one of those sets of releases are obsolete and that isn't clear on first read, if at all.

**Comment by gquintard** [comment]
@Bilge , please have a look at https://github.com/varnish/varnish-modules/blob/master/README.md , does it help a bit?

**Comment by Bilge** [comment]
I can't really comment on it because it's not part of any PR, it was already committed directly to `master`.

**Comment by Bilge** [comment]
@gquintard Why was this closed with no further comment? I have feedback on the readme but it would be easier to annotate in context. If that's not possible I can still write a summary here.

**Comment by gquintard** [comment]
Sorry, I took from your comments that you wouldn't be doing. You can comment on the comit directly if you want: https://github.com/varnish/varnish-modules/commit/6b9e04cbd48986bb87a877fee94b122ca3f7c088

**Comment by Bilge** [comment]
@gquintard Not at all. I promised I would review it and to that effect I now have. Hopefully you can find some useful feedback on that commit.

**Comment by Bilge** [comment]
@gquintard I see you took my suggestions into consideration. Just wanted to say it looks like you did a good job!

**Comment by gquintard** [comment]
Appreciated!
