### ISSUE TITLE
Provide vmod_str in 6.0-lts branch ?

### ISSUE THREAD

**Issue by yched** [varnish/varnish-modules#175]
The (now frozen) https://github.com/gquintard/libvmod-str repo provides branches for 4.0 / 4.1 / 5.0 / 5.1, and then before a 6.0 branch was published the code was moved here in varnish-modules but only for 6.5+

Would it be possible to provide a version of vmod_str for the 6.0 LTS ?

**Comment by gquintard** [comment]
there's no policy against it, but it's not a priority, if you can offer a PR to backport the module I'll be happy to merge it. It should be fairly straightforward as the vmod does do anything fancy

**Comment by yched** [comment]
Thanks for the quick merge !
