### ISSUE TITLE
Error with version 6.6 of Varnish

### ISSUE THREAD

**Issue by BorderCloud** [varnish/varnish-modules#184]
Hello

The version by default of Varnish with Centos 7 is now 6.6 (via yum update).

There are now errors with varnish-module during the compilation (with the last release for 6.5 but also with the version in the master).

Error with the release for 6.5:
https://github.com/BorderCloud/tft-virtuoso7-stable/runs/3026944403?check_suite_focus=true

Error with the master:
https://github.com/BorderCloud/tft-virtuoso7-stable/runs/3026710351?check_suite_focus=true

**Comment by gquintard** [comment]
Which varnish-modules branch are you using in both cases?

-- 
Guillaume Quintard

**Comment by BorderCloud** [comment]
> Which varnish-modules branch are you using in both cases?

with the release for 6.5:
```
git clone -b 0.17.1 https://github.com/varnish/varnish-modules.git
```

Error with the master:
```
git clone https://github.com/varnish/varnish-modules.git
```

**Comment by gquintard** [comment]
https://github.com/varnish/varnish-modules#installation

The varnish-modules master branch targets  the varnish-cache master branch,
and the varnish-module 0.17 release targets the varnish-cache 6.5 releases.

For varnish-cache 6.6, use either the 6.6 branch, or the 0.18 release

-- 
Guillaume Quintard

**Comment by BorderCloud** [comment]
Thanks, it works with:
`git clone --depth 1 --branch 6.6 https://github.com/varnish/varnish-modules.git`
