### ISSUE TITLE
[accept] VTC servers need to be started

### ISSUE THREAD

**Issue by gquintard** [varnish/varnish-modules#187]
otherwise, no macro, which is a problem for `-vcl+backend` which needs it

**Comment by gquintard** [comment]
fixed in 84490722c7b68113ef34281bb1cabc32471888f2

**Comment by aj-jwair** [comment]
Hi, we're unable to build release 0.18.0 on Alpine due to this issue. `make check` fails without the `-start` in `tests/accept/test01.vtc` and `tests/accept/test02.vtc`. Is this fix going to be ported into 0.18?

Interestingly, the tests pass on the Debian based image of Varnish.

**Comment by gquintard** [comment]
hi, the next varnish release is right around the corner, so this won't get back ported.

However, I did open an `alpine` PR to include `varnish-modules` in the repos, and so there's a patch downstream: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/24172/diffs
Of course, you can just build the package with that, it's even simpler.
