### ISSUE TITLE
update docs to reflect potential risk regarding Global variables after Varnish child panic

### ISSUE THREAD

**Issue by matheuzzy** [varnish/varnish-modules#190]
Hello!

Consider the following scenario: implement a maintenance open/close mechanism for load balancer (Varnish) using VMOD var. Be sure to keep the state after Varnish restart/reload!

Solution: 
- to update the running instance: curl varnish with desired load balancer mode
- update VCL file (a small part that contains sub vcl_init and is included in the main VCL file) to reflect the mode after start/reload

```
#!/usr/bin/env bash

set -e

echo "Write VCL lb mode"
echo "Set $1 in /var/www/lb_mode.vcl"

echo "sub vcl_init {
    var.global_set(\"lb_mode\", \"$1\");
}" > /var/www/lb_mode.vcl

echo "CURL local varnish to set new lb_mode in global var"
curl "http://127.0.0.1:6081/set_lb_mode/$1"
```

**The issue** occurs after a Varnish child panic for some (other) reasons -> **the global var value is lost** + the vcl_init routine is not called when child re-start

**Varnish Test Case:**
```
varnishtest "VCL: check global value after panic"

barrier b1 cond 2
barrier b2 cond 2

server s1 {
    rxreq
    txresp -hdr "Foo: bar" -body "abcdef\n"
    rxreq
    txresp -hdr "Panic: fetch" -body "012345\n"
    close

    barrier b1 sync
    accept
    rxreq
    txresp -hdr "Foo: bar" -body "abcdef\n"
    rxreq
    txresp -hdr "Panic: deliver" -body "012345\n"
    close

    barrier b2 sync
    accept
    rxreq
    txresp -hdr "Foo: foo" -body "abcdef\n"
} -start

varnish v1 -arg "-sdefault,1m" -vcl+backend {
    import vtc;
    import std;
    import var;
    sub vcl_init {
        var.global_set("load_balancer_mode","open");
        std.log("Init only once!");
    }
    sub vcl_recv {

        std.log(req.url);
        if (req.url ~ "^/set_lb_mode/") {
            var.global_set("load_balancer_mode", regsub(req.url, "^/set_lb_mode/(.*)$", "\1"));
            std.log("SET global var: " + var.global_get("load_balancer_mode"));
        }
    }

    sub vcl_backend_response {
        if (beresp.http.panic == "fetch") {
            vtc.panic("Had Panic header: " + beresp.http.panic);
        }
    }
    sub vcl_deliver {
        set resp.http.load_balancer_mode=var.global_get("load_balancer_mode");
        if (resp.http.panic == "deliver") {
            vtc.panic("Had Panic header: " + resp.http.panic);
        }
    }
} -start

varnish v1 -cliok "stop"
varnish v1 -cliok "start"
varnish v1 -wait-running
varnish v1 -expect MGT.child_panic == 0
varnish v1 -cliok "param.set feature +no_coredump"

client c1 {
    txreq -url "/set_lb_mode/closed"
    rxresp
    expect resp.http.load_balancer_mode == "closed"
    txreq -url "/foo"
    # Don't expect answer, the server crashed.
} -run

varnish v1 -wait-stopped
varnish v1 -cliok "panic.show"
varnish v1 -clijson "panic.show -j"
varnish v1 -cliok "panic.clear"
varnish v1 -expect MGT.child_panic == 1
varnish v1 -clierr 300 "panic.clear"
varnish v1 -cliok "start"
varnish v1 -wait-running
barrier b1 sync

client c1 {
    txreq -url "/"
    rxresp
    expect resp.http.load_balancer_mode == "closed"
    txreq -url "/foo"
    # Don't expect answer, the server crashed.
} -run

varnish v1 -wait-stopped
varnish v1 -cliok "panic.show"
varnish v1 -clijson "panic.show -j"
varnish v1 -cliok "panic.clear -z"
varnish v1 -expect MGT.child_panic == 0
varnish v1 -clierr 300 "panic.clear"
varnish v1 -cliok "start"
varnish v1 -wait-running
barrier b2 sync

client c1 {
    txreq -url "/"
    rxresp
    expect resp.http.load_balancer_mode == "closed"
    expect resp.http.foo == "foo"
} -run

varnish v1 -cliok "panic.clear -z"
varnish v1 -expectexit 0x20
```
PS: i didn't find a way to demonstrate the overwrite of vcl_ini part, but for sure is not re-read since std.log("Init only once!") shows just once.

**Comment by matheuzzy** [comment]
Hello! thanks for your reply.

My point is you have no option to keep that state if Varnish child panic.

If you store it in the global var -> sure, it will be lost
But If you re-write VCL dynamically and update **vcl vcl_init routine** - it will not be read on child restart. It will be read only if Varnish main service is restarted/reloaded, but child panic do not imply Varnish main service to do so. ( in my vtc  std.log("Init only once!"); shows  only once )

**Comment by gquintard** [comment]
> ^ I'm not sure that vcl_init is called at all because I don't see any output from std.log in the VTC run; Or maybe the custom defined one is not executed (just the build-in one)..?

Ye of little faith :-) When a panic occurs, the varnish child memory is gone, so you lose your cache of course, but also the `var` state, variables and so on, so if you don't go through `vcl_init`, there's no way access to `var` will work.

Let's see if I can convince that we indeed go through `vcl_init` with this `vtc`:

``` vcl
varnishtest "panic"

server s1 {} -start

shell {
	echo foo > ${tmpdir}/state
}

varnish v1 \
	-arg "-p auto_restart=on" \
	-arg "-p feature=+no_coredump" \
	-vcl+backend {
	import std;
	import vtc;

	sub vcl_init {
		std.log("vcl_init:" + std.fileread("${tmpdir}/state"));
	}

	sub vcl_recv {
		vtc.panic("boom");
	}
} -start

shell {
	echo bar > ${tmpdir}/state
}

varnish v1 -clierr 400 debug.panic.worker
delay 1
varnish v1 -cliok "panic.clear"

shell {
	varnishlog -g raw -d -n ${v1_name} | grep "vcl_init:bar"
}

varnish v1 -expectexit 0x40
```

The important steps are:
- put `foo` in the state file
- load the vcl, printing the content of the state file
- update the state file content
- panic
- check the logs to see that the updated file content were printing

The reason why you didn't see the second init in your vtc is probably that when the panic occurs, there's a gap in the log reading, and you lose a few line, but with `varnishlog -d` you can backlog and see that the lines were indeed written.

> By the way, what do you think about the example with "global variables as state flags" in the docs? maybe an extra info about how to store it's value after restart (or panic) is helpful? maybe no one else will go with a wrong similar solution as mine.

I'm honestly open to PRs, you got tripped by that one so your experience is relevant, however, be careful not to muddy the water too much. Describing the full solution will probably take double the current amount of documentation. So maybe just a line mentioning "you should also take care of persisting the information in case of a restart/panic" would be enough?

By the way, if persisting the data is important, again, use `redis`, `sqlite3`, `memcached` and the associated vmods

**Comment by matheuzzy** [comment]
thanks for you time @gquintard! 👍  
Since I found varnishtest I learned a lot and I trust it too much I think :)

Your VTC proved vcl init usage + **one more thing:** the content from std.fileread is not stored by the Varnish manager, so this a perfect solution to persist state after panic. ( funny is that I had this solution with std file, but I changed it a time ago ..)
