### ISSUE TITLE
varnish-modules-0.19.0 checks fails when built with gcc-12 on aarch64

### ISSUE THREAD

**Issue by ingvarha** [varnish/varnish-modules#194]
When fedora rawhide switched from gcc-11 to gcc-12, make check started failing on aarch64, with tests segfaulting.

https://kojipkgs.fedoraproject.org//work/tasks/9989/81449989/build.log

Ingvar

**Comment by Dridi** [comment]
Looks like segmentation faults in varnishtest.

**Comment by Dridi** [comment]
Not necessarily, since not all test cases failed, but quite likely.

**Comment by ingvarha** [comment]
Last build of varnish was before the gcc update, so this wasn't catched then. It fails now:

https://kojipkgs.fedoraproject.org//work/tasks/8869/81758869/build.log

**Comment by gquintard** [comment]
thanks @ingvarha , since that's an upstream issue (https://github.com/varnishcache/varnish-cache/issues/3776), I'll close this
