### ISSUE TITLE
varnish modules version 0.14?

### ISSUE THREAD

**Issue by dbu** [varnish/varnish-modules#200]
I maintain a library that i test automatically against legacy varnish versions. The build script used to download the modules for varnish 5 from https://download.varnish-software.com/varnish-modules/ - as per #113

i noticed that the download.varnish-software.com domain no longer exists in DNS.

is there a place where i can download the modules in version 0.14?

**Comment by gquintard** [comment]
Hi @dbu , long time no see!

mandatory remark: Varnish 5 has been EOL for while, you should really push users to move away from it, yadda yadda.

download.varnish-software.com doesn't exist anymore, but thankfully, [0.14.0](https://github.com/varnish/varnish-modules/tree/0.14.0) is a [github tag](https://github.com/varnish/varnish-modules/tags), so you can download the code directly: https://github.com/varnish/varnish-modules/archive/0.14.0.zip

It's not a proper dist tarball, just the source code, but that should be enough, shouldn't it?

**Comment by dbu** [comment]
hi @gquintard, yep indeed. still a happy varnish user though :-)

oh, i did not realize that 0.14 was available on github. maybe we used the other location for some even older builds that had no tags. the build of 0.14 works just fine with varnish 5 https://github.com/FriendsOfSymfony/FOSHttpCache/runs/7202432455?check_suite_focus=true :+1: 

myself i am running on a recent varnish, but i build the package even with varnish 3 :-D

i imagine some people are stuck on old installations. and its usually not much effort for me to keep supporting it. when we add new functionality, we will drop the EOL versions though.
