### ISSUE TITLE
Error in makefile

### ISSUE THREAD

**Issue by codessauro** [varnish/varnish-modules#213]
./configure   
configure: error: Varnish version 7.0.0 or higher is required.
root@root:/etc/varnish/varnish-modules# sudo make
make: *** No targets specified and no makefile found.  Stop.

root@root:/etc/varnish/varnish-modules# varnishd -V
varnishd (varnish-7.0.3 revision 6a4c6a5c7e6c544cab8)
Copyright (c) 2006 Verdens Gang AS

root@root:/etc/varnish/varnish-modules# make
make: *** No targets specified and no makefile found.  Stop.

**Comment by gquintard** [comment]
Hi,

if the `configure` step fails, there's no point in trying to call `make` (which you shouldn't do through `sudo`). How was `varnish` installed?

**Comment by codessauro** [comment]
Hi I have Installed Varnish 7.0.3 from repository OK, after have installed some packages 
pkg-config  
autoconf 
automake 
libtool  
libvarnishapi-dev 
After get location of 
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/

./bootstrap
`root@qeblafaycach01:/etc/varnish/varnish-modules# ./bootstrap
+ mkdir -p m4
+ aclocal -I m4 -I /usr/share/aclocal
+ libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
+ autoheader
+ automake --add-missing --copy --foreign
configure.ac:14: installing 'build-aux/compile'
configure.ac:10: installing 'build-aux/missing'
src/Makefile.am: installing 'build-aux/depcomp'
+ autoconf
`
After ./configure 

 Where not create file makefile

**Comment by codessauro** [comment]
I find not have installed package phyton-sphinx, my fault

**Comment by gquintard** [comment]
thanks for reporting, all solved then?

**Comment by gquintard** [comment]
assuming all is good, closing
