### ISSUE TITLE
Update saintmode configuration language for inclusivity

### ISSUE THREAD

**Issue by benzvan** [varnish/varnish-modules#217]
I was cleaning up some of the archaic language in our projects and discovered we're setting the `saintmode.blacklist` value on our varnish containers. This terminology should be updated to something more inclusive and more descriptive of its purpose. It would make sense to deprecate the configuration field and replace it with `backend_sick_timer` or similar descriptive language. Honestly the whole `saint`, `grace`, etc. metaphor could be more descriptive.

Instances in code:
https://github.com/search?q=repo%3Avarnish%2Fvarnish-modules%20blacklist&type=code

More details:
https://www.splunk.com/en_us/blog/learn/blacklist-whitelist-inclusivity.html

**Comment by gquintard** [comment]
I'm in favor, would you care opening a PR for it?

**Comment by gquintard** [comment]
thankfully, you shouldn't have to do C, [Varnish 7.1](https://github.com/varnishcache/varnish-cache/blob/master/doc/changes.rst#varnish-cache-710-2022-03-15) introduced `$Alias` that should do your bidding. You can see it used in [vmod-cookie](https://github.com/varnishcache/varnish-cache/blob/master/vmod/vmod_cookie.vcc)

That will leave the old names around for a while, but I don't want to break users without notice

**Comment by benzvan** [comment]
Oh cool! It looks like I can just update the aliases and documentation and leave the code the same, so here's a [draft PR](https://github.com/varnish/varnish-modules/pull/218) doing that. Let me know if this is what you were thinking. Updating the code looks pretty straightforward but I'm not sure I can run the tests locally right now.

**Comment by gquintard** [comment]
cleaning, the associated PR has been merged
