### ISSUE TITLE
7.6.1: ABI mismatch

### ISSUE THREAD

**Issue by iammeken** [varnish/varnish-modules#228]
```
varnishd -V
varnishd (varnish-7.6.1 revision c3d5882003eb87e5e93dc09fb9513ca96db3ca3c)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2024 Varnish Software
Copyright 2010-2024 UPLEX - Nils Goroll Systemoptimierung
import tcp;
```

Message from VCC-compiler:
Incompatible VMOD tcp
        File name: /usr/lib/varnish/vmods/libvmod_tcp.so
        ABI mismatch, expected <Varnish 7.6.1 c3d5882003eb87e5e93dc09fb9513ca96db3ca3c>, got <Varnish 7.6.0 ed1243ca162a7b1d975bc0332f0d66d33f0bc78e>

**Comment by iammeken** [comment]
Sorry, my mistake, should run` make clean` first.

**Comment by gquintard** [comment]
Glad you found the issue :-)
