### ISSUE TITLE
varnish-module test fail on i386 with varnish 4.1.3

### ISSUE THREAD

**Issue by jbfavre** [varnish/varnish-modules#28]
While backporting `varnish-module` 0.9.1 for Debian Jessie, `src/tests/cookie/08-overflow.vtc` fails on i386

Full test log is available here: https://gist.github.com/jbfavre/c753336f4fc3c898ed7c066dd0b7b8a1

**Comment by lkarsten** [comment]
Hi. Thanks for the report.

This is not surprising, the test case is rather brittle.

Varnish makes this complicated by changing parameters on startup on 32bit platofrms: https://github.com/varnishcache/varnish-cache/blob/36e8ac2fc77e8f8b63ea0a41b14d6555ea50433c/bin/varnishd/mgt/mgt_main.c#L442

You can skip the test case if you want. I'll have a look and see if we can test it some other way.

**Comment by fgsch** [comment]
Moved to #35.

**Comment by lkarsten** [comment]
To keep @jbfavre  in the loop, #35 was closed/fixed with cdf9967 today. This should take care of this issue as well.

Thanks again for reporting it.

**Comment by jbfavre** [comment]
@lkarsten thanks for the update. That's great news :)
