### ISSUE TITLE
vmod_tcp is not portable

### ISSUE THREAD

**Issue by feld** [varnish/varnish-modules#30]
vmod_tcp doesn't build on FreeBSD. It uses SOL_TCP which is Linux-specific. Is this module intended to be portable or does it solve a Linux-specific issue?

**Comment by gquintard** [comment]
It would be nice if it were portable, it allows the vcl to pace requests instead of pushing data as fast as possible.

**Comment by feld** [comment]
This is a duplicate of #7

closing.
