### ISSUE TITLE
0.9.1 tarball not made by make dist

### ISSUE THREAD

**Issue by ingvarha** [varnish/varnish-modules#32]
varnish-modules-0.9.1.tar.gz as found at https://github.com/varnish/varnish-modules/releases is a bit strange. It extracts to "varnish-modules-varnish-modules-0.9.1/". It also seems to be a "raw" checkout.

Running
./bootstrap && ./configure && make && make dist  

produces a "normal" release tarball.

**Comment by fgsch** [comment]
Yes, that tarball comes from github. Having varnish-module twice is a side effect of it.
Please note this is similar to the way varnish-cache is handled.

Not sure what @lkarsten wants to do here.

**Comment by ingvarha** [comment]
@fgsch no, this is not the way varnish-cache is handled. When there is a release of varnish-cache, the github checkout is made into a release tarball (make dist), and then released at https://repo.varnish-cache.org/source/ . It would be great if @lkarsten did the same for varnish-modules.

**Comment by ingvarha** [comment]
ah, it IS released properly, at https://download.varnish-software.com/varnish-modules/ . So I'm just rambling. Please ignore :-)

**Comment by fgsch** [comment]
My response was specifically wrt tarballs in github. Anyway, sounds like is a nop now.
