### ISSUE TITLE
Build on el5

### ISSUE THREAD

**Issue by ingvarha** [varnish/varnish-modules#34]
For RHEL5 and clones, I need the following to make varnish-modules build. Is it possible to automate this by autoconf? (I do understand that rl5 does not have high prio.)

* Add -D_GNU_SOURCE to CFLAGS
* Add the following patch
https://ingvar.fedorapeople.org/varnish/varnish-modules-0.9.0-add_missing_TCP_CONGESTION_on_el5.patch

Ingvar

**Comment by fgsch** [comment]
Rather than adding _GNU_SOURCE blindly, can we get the list of files that fail to compile when it's missing?

**Comment by ingvarha** [comment]
Seems it's only vmod_cookie.c. The rest compiles fine without.

$ gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -I../src/foreign -Wall -Werror -Wunused-parameter -Wmissing-prototypes   -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -MT vmod_cookie.lo -MD -MP -MF .deps/vmod_cookie.Tpo -c -o vmod_cookie.lo vmod_cookie.c
cc1: warnings being treated as errors
vmod_cookie.c: In function ‘vmod_parse’:
vmod_cookie.c:109: warning: implicit declaration of function ‘strndup’
vmod_cookie.c:109: warning: incompatible implicit declaration of built-in function ‘strndup’
vmod_cookie.c: In function ‘vmod_filter_except’:
vmod_cookie.c:284: warning: incompatible implicit declaration of built-in function ‘strndup’

vs

$ gcc -std=gnu99 -D_GNU_SOURCE -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -I../src/foreign -Wall -Werror -Wunused-parameter -Wmissing-prototypes   -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -MT vmod_cookie.lo -MD -MP -MF .deps/vmod_cookie.Tpo -c -o vmod_cookie.lo vmod_cookie.c && echo SUCCESS
SUCCESS

**Comment by fgsch** [comment]
I've committed a fix for strndup().

Re TCP_CONGESTION, can you share the netinet/tcp.h from EL5?

**Comment by ingvarha** [comment]
netinet/tcp.h from el5: https://ingvar.fedorapeople.org/netinet_tcp.h.el5
