### ISSUE TITLE
0.9.1 tests/cookie/08-overflow.vtc fails on 32bit

### ISSUE THREAD

**Issue by ingvarha** [varnish/varnish-modules#35]
tests/cookie/08-overflow.vtc fails on 32bit

Environment: varnish-modules-0.9.1 with varnish-4.1.3 on fedora rawhide/armhfp
Example build logs: 
https://kojipkgs.fedoraproject.org//work/tasks/5551/15185551/build.log
https://kojipkgs.fedoraproject.org//work/tasks/5780/15185780/build.log
https://kojipkgs.fedoraproject.org//work/tasks/5901/15185901/build.log

**Comment by ingvarha** [comment]
Might even be a 32bit problem. make check on i686 also fails:
https://kojipkgs.fedoraproject.org//work/tasks/6178/15186178/build.log

**Comment by ingvarha** [comment]
For what it's worth: The culprit is the "Insane 6KB cookie value". A cookie of 5982 bytes works fine, while a 5983 long one fails. Reproduced on i686 and amv7l.

**Comment by ingvarha** [comment]
duh

1003 Error           c workspace_client overflow

That's quite a good hint

So after reading the varnishd manual, and upping workspace_client to 32k (defaults to 16k on 32bit, 64k on 64bit) I solved the problem, something by something like this:

varnish v1 -cliok "param.set workspace_client 32k"

**Comment by fgsch** [comment]
So with this change is passing in both 32 and 64 bits?
