### ISSUE TITLE
Move curl vmod into this collection

### ISSUE THREAD

**Issue by andrerom** [varnish/varnish-modules#46]
Would be useful to be able to cleanly do curl calls with this collection on varnish itself for hash lookups relevant to a request.

**Comment by Dridi** [comment]
Hi,

It would conflict with the first non-goal from the [README](https://github.com/varnish/varnish-modules#administrativa):

> Expressed non-goals are:
>
> - Import vmods that require external libraries, like curl or geoip. This collection should be simple and maintenance free to run.

Dridi

**Comment by andrerom** [comment]
Ok, makes sense, overlooked that part.

Other ways we could expose a way to do cached sub requests in VCL? We _(eZ & FOSHttpCache lib)_ currently use restart but were told by a Varnish employee we should rather use curl so VCL is easier to read, however we rather not as long as it implies installing from source, `varnish-modules` was a promising direction for things like this _(and easier access to xkey)_.

**Comment by gquintard** [comment]
I was probably the one saying that :-)

Using curl would indeed increase readability, but I realized afterwards the benefit of using restart: you get to cache authorizations.

I still think there's a better way, possibly using vcl labels. Would you mind sending an email to varbilnsh-misc, linking the currently used vcl, so we can have a look at and discuss it together?
