### ISSUE TITLE
vmod_header: Issue with remove Set-Cookie

### ISSUE THREAD

**Issue by ucola** [varnish/varnish-modules#48]
Hi all

I want to ask something
We have a lot of same Set-Cookie and want to remove the dublicate, because Safari have issues with double items.

`
Set-Cookie:Drupal.visitor.usemobile=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Set-Cookie:Drupal.visitor.backgroundnum=0; expires=Tue, 21-Nov-2017 12:45:45 GMT; Max-Age=31535999; path=/
Set-Cookie:Drupal.visitor.usemobile=0; expires: Session; Max-Age=2592000; path=/
Set-Cookie:Drupal.visitor.usedesktop=1; expires=Wed, 21-Dec-2016 12:45:45 GMT; Max-Age=2592000; path=/
Set-Cookie:Drupal.visitor.useapp=0; expires: Session; Max-Age=2592000; path=/
Set-Cookie:Drupal.visitor.usedesktop=1; expires: Session; Max-Age=2592000; path=/
Set-Cookie:Drupal.visitor.useapp=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Set-Cookie:Drupal.visitor.usedesktop=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Set-Cookie:Drupal.visitor.usemobile=0; expires=Wed, 21-Dec-2016 12:45:45 GMT; Max-Age=2592000; path=/
Set-Cookie:Drupal.visitor.useapp=0; expires=Wed, 21-Dec-2016 12:45:45 GMT; Max-Age=2592000; path=/
Set-Cookie:Drupal.visitor.usedesktop=0; expires=Wed, 21-Dec-2016 12:45:45 GMT; Max-Age=2592000; path=/
Set-Cookie:Drupal.visitor.usemobile=0; expires=Wed, 21-Dec-2016 12:45:45 GMT; Max-Age=2592000; path=/
Set-Cookie:Drupal.visitor.useapp=0; expires=Wed, 21-Dec-2016 12:45:45 GMT; Max-Age=2592000; path=/
`

now we want on vcl_deliver remove all this (also all with Drupal.visitor.*) and set it manualy. We try different ways, i.e.
`
if (resp.http.Set-Cookie) {
    header.remove(resp.http.Set-Cookie, ".visitor.");
}
`

But nothing works. Can somebody help us? thank you

**Comment by aondio** [comment]
Hi @ucola, this is not the right channel to ask about this.
If you want to have some suggestions/solutions for your problem, please drop an email to varnish-misc@varnish-cache.org.

Thanks.
