### ISSUE TITLE
Question about update

### ISSUE THREAD

**Issue by Rod-Gomes** [varnish/varnish-modules#50]
I do not know if this is the right place to ask that question. But I did not find anywhere else to do, so ... 

I would like to know if after installing these modules them will update automatically or if I have to do a new installation every time it updates.

And how do I know the installed version?

Thank you.

**Comment by aondio** [comment]
Hi @Rod-Gomes, to ask such type of questions you should send an email to 	varnish-misc@varnish-cache.org.

Since we are at it, I'll reply to this question: you will have to run an update whenever you want to update these modules.

**Comment by Rod-Gomes** [comment]
Thank you @aondio . Next time I'll ask the question in the right place. :)
