### ISSUE TITLE
Move contents from docs/foo.rst into src/foo.vcc

### ISSUE THREAD

**Issue by lkarsten** [varnish/varnish-modules#6]
We have both docs/foo.rst which contain a lot of text. 

During builds vmodtool.py will create a vmod_foo.man.rst file based on our vmod_foo.vcc files. 
These man pages are used and distributed. The old README.rst file isn't used for much, and has at times duplicated content.

We should consider moving the contents from docs/foo.rst and put them into src/foo.vcc instead.

**Comment by aondio** [comment]
I can do this.

**Comment by lkarsten** [comment]
Related notices from lintian while building debs:
```
W: varnish-plus: manpage-has-bad-whatis-entry usr/share/man/man3/vmod_softpurge.3.gz
W: varnish-plus: manpage-section-mismatch usr/share/man/man3/vmod_softpurge.3.gz:3 3 != VMOD
```

**Comment by aondio** [comment]
For the record, I'm doing the changes here: https://github.com/aondio/varnish-modules/tree/man_pages

**Comment by aondio** [comment]
Is there a way to not generate "vmod_*.man.rst"?

**Comment by Dridi** [comment]
I don't think there is.

**Comment by aondio** [comment]
Here is the PR: https://github.com/varnish/varnish-modules/pull/8

**Comment by lkarsten** [comment]
I've moved the changes from @aondio 's .vcc files into master and commited them now. Old manual .rst files in docs/ are deleted, and the ones built by vmodtool.py have been checked in.

People should be able to find the documentation online now. I'm not overly enthusiastic to how this turned out in the end, but I think it is an improvement overall. We need to fix vmodtool.py to get this right/clean.
