### ISSUE TITLE
Purged objects show number of runs?

### ISSUE THREAD

**Issue by AceWT** [varnish/varnish-modules#62]
Testing with this:
set req.http.n-gone = xkey.purge(req.http.xkey-purge);

Http request:
xkey: a1 a2 a3

Purge request:
Xkey-purge: a1
Result: 1

Purge request 2:
Xkey-purge: a1 a2
Result: 2

Int returned from xkey.purge is actually number of runs For every cached object?

**Comment by gquintard** [comment]
https://github.com/varnish/varnish-modules/blob/master/src/vmod_xkey.vcc#L97
