### ISSUE TITLE
warning: macro `AM_EXTRA_RECURSIVE_TARGETS' not found in library

### ISSUE THREAD

**Issue by FireDrunk** [varnish/varnish-modules#63]
```bash
warning: macro 'AM_EXTRA_RECURSIVE_TARGETS' not found in library
```

This error is produced by the bootstrap script. This macro is only available in automake 1.13.
The default for CentOS 6 is still 1.11, which means you cannot compile the modules on CentOS6.

Is this intentional?

**Comment by Dridi** [comment]
Yes, this is intentional. Building from git requires a modern-enough platform, if you only plan to install the modules you should grab the latest release archive:

https://download.varnish-software.com/varnish-modules/

As commented in the README, you only need to run the bootstrap script from git.
