### ISSUE TITLE
Compile error with vmod_tcp on non-linux systems

### ISSUE THREAD

**Issue by quintonparker** [varnish/varnish-modules#7]
It was just last week that I was compiling a dozen vmods. Thanks for this!

I guess y'all don't care too much for supporting OSX (as a varnish development environment) but I can dream, right?

This is my error output when trying to run `make check` and/or `make install` against varnish 4.1.2 on OSX 10.10.5

``` bash
vmod_tcp.c:29:18: error: variable has incomplete type 'struct tcp_info'
        struct tcp_info tcpinfo;
                        ^
vmod_tcp.c:29:9: note: forward declaration of 'struct tcp_info'
        struct tcp_info tcpinfo;
               ^
vmod_tcp.c:30:19: error: invalid application of 'sizeof' to an incomplete type 'struct tcp_info'
        socklen_t tlen = sizeof(struct tcp_info);
                         ^     ~~~~~~~~~~~~~~~~~
vmod_tcp.c:29:9: note: forward declaration of 'struct tcp_info'
        struct tcp_info tcpinfo;
               ^
vmod_tcp.c:31:35: error: use of undeclared identifier 'SOL_TCP'
        if (getsockopt(ctx->req->sp->fd, SOL_TCP, TCP_INFO,
                                         ^
vmod_tcp.c:31:44: error: use of undeclared identifier 'TCP_INFO'
        if (getsockopt(ctx->req->sp->fd, SOL_TCP, TCP_INFO,
                                                  ^
vmod_tcp.c:59:18: error: variable has incomplete type 'struct tcp_info'
        struct tcp_info tcpinfo;
                        ^
vmod_tcp.c:59:9: note: forward declaration of 'struct tcp_info'
        struct tcp_info tcpinfo;
               ^
vmod_tcp.c:60:19: error: invalid application of 'sizeof' to an incomplete type 'struct tcp_info'
        socklen_t tlen = sizeof(struct tcp_info);
                         ^     ~~~~~~~~~~~~~~~~~
vmod_tcp.c:59:9: note: forward declaration of 'struct tcp_info'
        struct tcp_info tcpinfo;
               ^
vmod_tcp.c:61:35: error: use of undeclared identifier 'SOL_TCP'
        if (getsockopt(ctx->req->sp->fd, SOL_TCP, TCP_INFO,
                                         ^
vmod_tcp.c:61:44: error: use of undeclared identifier 'TCP_INFO'
        if (getsockopt(ctx->req->sp->fd, SOL_TCP, TCP_INFO,
                                                  ^
vmod_tcp.c:92:48: error: use of undeclared identifier 'TCP_CONGESTION'
        if (setsockopt(ctx->req->sp->fd, IPPROTO_TCP, TCP_CONGESTION, strategy, l) < 0) {
                                                      ^
vmod_tcp.c:100:48: error: use of undeclared identifier 'TCP_CONGESTION'
        if (getsockopt(ctx->req->sp->fd, IPPROTO_TCP, TCP_CONGESTION,
                                                      ^
10 errors generated.
make[1]: *** [vmod_tcp.lo] Error 1
make: *** [check-recursive] Error 1
```

Help. Please?

**Comment by Dridi** [comment]
Random googling [1] says OSX doesn't support those sock opts. Not my call, but it looks very unlikely to be supported (eg. turned into NOOPs) in this vmod.

[1] http://starlet.deltatel.ru/~laishev/work/iperf3/tcp_info.c

**Comment by lkarsten** [comment]
Hi.

Compile out of the box on OS X should definitively work. My intention when adding vmod-tcp was either to get some autoconf going and skip building it on non-linux, or simply ifdef it into noop. Didn't get that far, I'm afraid.

Working socket pacing on Linux is why it is there, the rest is rather esoteric.

Anyone want to do the work?

**Comment by lkarsten** [comment]
I forgot to mention, if you needed a workaround it isn't hard to disable it.

A quick hack involves remove the libvmod_tcp.la from vmod_LTLIBRARIES in src/Makefile.am and rerun `./bootstrap` and `./configure`. Other vmod_tcp lines can be removed as well, but vmod_LTLIBRARIES should suffice for building the others.

**Comment by quintonparker** [comment]
@lkarsten thanks!

**Comment by fgsch** [comment]
I will take a look. I Know how to fix some of the issues.

**Comment by feld** [comment]
A quick Google indicates that IPPROTO_TCP might be a portable replacement for SOL_TCP, but I haven't really investigated much further to outline the differences.

**Comment by lkarsten** [comment]
I think the way forward here is to add autoconf stances to only build vmod-tcp on linux.

Help with this would be appreciated.

**Comment by Dridi** [comment]
@lkarsten I had a quick look, and it should be fairly trivial to add conditionals for building the module.

For the test suite, with some shell trick I can also skip the TCP tests although I'd rather go for something like varnishcache/Varnish-Cache#2044. Feel free to assign this to me if it can wait for a couple weeks.

**Comment by daghf** [comment]
@fgsch OK to hand this over to @Dridi ?

**Comment by fgsch** [comment]
Sure.

**Comment by quintonparker** [comment]
waiting patiently :trollface:

**Comment by Dridi** [comment]
I'll gladly review your pull request :trollface:

**Comment by ddeboer** [comment]
@Dridi Could you open a PR with your commit, so we can discuss it? We need to make vmod_tcp conditional for Alpine, too (the Docker-friendly Linux distro): see #45.

**Comment by Dridi** [comment]
Already done but a while ago. It will conflict with recent changes anyway so I'll come up with a new patch.
