### ISSUE TITLE
vmod_vsthrottle: 5xx errors counted as request?

### ISSUE THREAD

**Issue by 2ge** [varnish/varnish-modules#71]
Hi,

got a question - if for some reason all webservers are down, and varnish returns 5xx for request, it is counted as valid request in vsthrottle ? It is possible to count just 2xx responses ?

Thanks

**Comment by gquintard** [comment]
@2ge, sorry for the late reply, next time please try to use the varnish-misc mailing list, we tray to keep the bug trackers for, well, bugs.

To answer your question, the throttle is counted when the function is called.
