### ISSUE TITLE
Failed check on 02-congestion-vtc on master@937240f

### ISSUE THREAD

**Issue by FGM** [varnish/varnish-modules#80]
I just built the modules from commit 937240f (current master), and I get a failed test on 02-congestion.vtc during make check.

Varnish itself was built a few minutes ago from current master too.

I've attached the test-suite.log in case it could help.

[test-suite.log.txt](https://github.com/varnish/varnish-modules/files/1159337/test-suite.log.txt)

FWIW, `uname -a` output 

    Darwin FGM-GUI16.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Comment by Dridi** [comment]
Sorry for the late response, this should be fixed in the master branch now.
