### ISSUE TITLE
Unable to install on Ubuntu 16.04 with Varnish 5.1.3

### ISSUE THREAD

**Issue by saraswat40** [varnish/varnish-modules#82]
Hi Guys,

I'm trying to install varnish-modules on Ubuntu 16.04 with Varnish 5.1.3. Varnish 5.13 was upgraded from Varnish 4.1 using packages provided by package-cloud. Let me know what I missed.

Thanks
Prashant

$ sudo make install
Making install in src
make[1]: Entering directory '/home/ubuntu/varnish-modules/varnish-modules/src'
: vmod_bodyaccess.man.rst vmod_bodyaccess.3
: vmod_cookie.man.rst vmod_cookie.3
: vmod_header.man.rst vmod_header.3
: vmod_saintmode.man.rst vmod_saintmode.3
: vmod_softpurge.man.rst vmod_softpurge.3
: vmod_tcp.man.rst vmod_tcp.3
: vmod_var.man.rst vmod_var.3
: vmod_vsthrottle.man.rst vmod_vsthrottle.3
: vmod_xkey.man.rst vmod_xkey.3
make[2]: Entering directory '/home/ubuntu/varnish-modules/varnish-modules/src'
make[2]: Nothing to be done for 'install-exec-am'.
: vmod_bodyaccess.man.rst vmod_bodyaccess.3
: vmod_cookie.man.rst vmod_cookie.3
: vmod_header.man.rst vmod_header.3
: vmod_saintmode.man.rst vmod_saintmode.3
: vmod_softpurge.man.rst vmod_softpurge.3
: vmod_tcp.man.rst vmod_tcp.3
: vmod_var.man.rst vmod_var.3
: vmod_vsthrottle.man.rst vmod_vsthrottle.3
: vmod_xkey.man.rst vmod_xkey.3
 /bin/mkdir -p '/usr/share/man/man3'
 /usr/bin/install -c -m 644 ./vmod_bodyaccess.3 ./vmod_cookie.3 ./vmod_header.3 ./vmod_saintmode.3 ./vmod_softpurge.3 ./vmod_tcp.3 ./vmod_var.3 ./vmod_vsthrottle.3 ./vmod_xkey.3 '/usr/share/man/man3'
/usr/bin/install: cannot stat './vmod_bodyaccess.3': No such file or directory
/usr/bin/install: cannot stat './vmod_cookie.3': No such file or directory
/usr/bin/install: cannot stat './vmod_header.3': No such file or directory
/usr/bin/install: cannot stat './vmod_saintmode.3': No such file or directory
/usr/bin/install: cannot stat './vmod_softpurge.3': No such file or directory
/usr/bin/install: cannot stat './vmod_tcp.3': No such file or directory
/usr/bin/install: cannot stat './vmod_var.3': No such file or directory
/usr/bin/install: cannot stat './vmod_vsthrottle.3': No such file or directory
/usr/bin/install: cannot stat './vmod_xkey.3': No such file or directory
Makefile:872: recipe for target 'install-man3' failed
make[2]: *** [install-man3] Error 1
make[2]: Leaving directory '/home/ubuntu/varnish-modules/varnish-modules/src'
Makefile:1168: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/ubuntu/varnish-modules/varnish-modules/src'
Makefile:541: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by behid** [comment]
Think you need to install python-docutils before running configure to make it work.

**Comment by Dridi** [comment]
It looks like you are building from git, you should build a release tarball instead. Releases are shipped with the manual already built.

**Comment by saraswat40** [comment]
@behid many thanks!!. The python-docutils solved the issue
