### ISSUE TITLE
bootstrap fails AM_EXTRA_RECURSIVE_TARGETS indefined macro

### ISSUE THREAD

**Issue by andreasbaumann** [varnish/varnish-modules#86]
bootstrap checks for automake 1.9, AM_EXTRA_RECURSIVE_TARGETS needs at least 1.11.1 (I think).

**Comment by Dridi** [comment]
You should not need automake unless you are working on a git clone, please download releases from https://download.varnish-software.com/varnish-modules/ as documented in the readme.

**Comment by andreasbaumann** [comment]
Then maybe the version in bootstrap should be increased accordingly?

**Comment by andreasbaumann** [comment]
and in configure.ac? AM_INIT_AUTOMAKE([1.11 foreign])

**Comment by Dridi** [comment]
Agreed, those details need attention, which is why I didn't close with my last comment.

**Comment by andreasbaumann** [comment]
Using https://wiki.centos.org/AdditionalResources/Repositories/SCL:

```
yum install python27
yum install devtoolset-4
scl enable devtoolset-4 bash
scl enable python27 bash
./bootstrap 
+ mkdir -p m4
+ aclocal -I m4 -I /usr/share/aclocal
+ libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
+ autoheader
+ automake --add-missing --copy --foreign
+ autoconf
./configure
checking for a Python interpreter with version >= 2.7... python
```

This gives me a modern autotool environment for Centos.
