### ISSUE TITLE
bulding fails on Centos 6

### ISSUE THREAD

**Issue by andreasbaumann** [varnish/varnish-modules#87]
checking for a Python interpreter with version >= 2.7... none
configure: error: Python >= 2.7 is required.

I realize that python coming on Centos 6 is old. But on the other hand I would try to
support old distributions.

What exactly needs Python? Can it be disabled? Is is only needed to build the documentation,
as vmods are pure C modules.

**Comment by andreasbaumann** [comment]
Ah, I see. This check for Python is in /usr/share/aclocal/varnish.m4:

```
# _VARNISH_CHECK_PYTHON
# ---------------------
AC_DEFUN([_VARNISH_CHECK_PYTHON], [
```
        AM_PATH_PYTHON([2.7], [], [ 
                AC_MSG_ERROR([Python >= 2.7 is required.])
        ])

])

**Comment by Dridi** [comment]
Indeed, VMODs are written in C but the C interface is generated by `vmodtool.py` provided by the Varnish installation. CentOS 6 ships "Python 2.6 + back-ports" that is technically enough for Varnish's Python needs, but we can't really check this corner case.

Can you install Python 3? I don't remember whether it is available on el6.

**Comment by andreasbaumann** [comment]
Ok. I'm trying with SCL..

**Comment by andreasbaumann** [comment]
https://wiki.centos.org/SpecialInterestGroup/SCLo/CollectionsList
yum install python27
scl enable python27 bash

yep. Problem solved. thanks.
