### ISSUE TITLE
vmod_header can be used in vcl_backend_fetch?

### ISSUE THREAD

**Issue by redbox-cdn** [varnish/varnish-modules#90]
I would like to control bereq header below.(varnish4.1x)

```
header.append(bereq.http.Accept-Encoding, "aaa");
header.append(bereq.http.Accept-Encoding, "bbb");
```

But  bereq.http.Accept-Encoding header is "aaa". (not "aaa,bbb")
is it possible to handle the bereq using vmod_header ?

**Comment by gquintard** [comment]
Let's keep this bug tracker for bugs, please use https://varnish-cache.org/lists/mailman/listinfo/varnish-misc for such questions.
