### ISSUE TITLE
Blocking clients for a specified duration

### ISSUE THREAD

**Issue by Rod-Gomes** [varnish/varnish-modules#94]
> [vmod-vsthrottle] Add an optional block parameter to vsthrottle.is_denied, to permit blocking clients for a specified duration when the request rate threshold is reached.

How I use this?

**Comment by nigoroll** [comment]
RTFM ? https://github.com/varnish/varnish-modules/blob/master/src/vmod_vsthrottle.vcc#L121

**Comment by Rod-Gomes** [comment]
Yes, Thank you!
