### ISSUE TITLE
Can't run configure in version 0.13.0

### ISSUE THREAD

**Issue by colas31** [varnish/varnish-modules#97]
Hello, 

I'm trying to install the last varnish-module 0.13.0, but I thing it's missing the configure file

I have donwloaded this tarball https://download.varnish-software.com/varnish-modules/varnish-modules-0.13.0.tar.gz
When I'm running ./configure I get this error : 
`/bin/bash: ./configure: Aucun fichier ou dossier de ce type`

However I succeed to install the previous version.

Thank for your help.

**Comment by Dridi** [comment]
Bonjour,

The release archive is wrong, we will update it with a proper one.

Thanks for reporting!

**Comment by colas31** [comment]
Thank you for your quick reply and a quick reaction !

**Comment by Dridi** [comment]
@dmatetelki fixed it, you should be fine now. Somehow I forgot to close this ticket on Tuesday...
